### ISSUE TITLE
few comments

### ISSUE THREAD

**Issue by jsbain** [chriswilson1982/black-and-white#11]
1) occasionally, i get a louder than usual lock noise, and the flip seems to happen wrong, like it locks the wrong cell.  Could be my fat fingers, but It seems to come with an extra loud buzz..
2) It would be nice to have a few second warning sound.  On the later stages, I have run out of time unexpectedly when trying to plan a move.
3) I noticed this is only a 1x game on the ipad -- any thoughts of making a regular resolution version?  You may get more visbility that way in the app store.  Or is this a template limitation?
4) What exactly are the rules regarding score based powerups?

**Comment by jsbain** [comment]
5) also, when viewing high score, you might want to disable the button after it is pressed once, or pop up a waiting box which prevents further interaction, until the screen is dismissed.  I pressed high score a few times until it loaded, then it popped up 4 times in a row!

**Comment by jsbain** [comment]
re 1: i think i csn reproduce this when tapping exactly on a horizontal intersection between two verticslly stacked cells.  then, both cells change at the same time.  perhaps loop on line 1286 should use an inset bbox, or should break loop after first hit.  also, might want to verify that square bboxes are non overlapping.

**Comment by chriswilson1982** [comment]
Thanks very much for your comments and interest. I have released a version to the App Store which you can get for free at https://appsto.re/gb/ERkSbb.i

The GitHub version is a little behind the released version. On the released version you'll find the screen layout is better on smaller phones and iPad (though still 1x), there is a global high score table and there are a few other refinements.

I'm working on version 1.1 so I appreciate the input. 

In response:

1) I've noticed this myself, and hat it doesn't happen horizontally. I think I'll try an inset bbox.

2) A great idea! I'll implement this.

3) Now I understand the template and screen layouts a bit more, I think I can make it a universal app at some point.

4) I'm going to change the instructions screen to a local html file via a webview and aim for more detailed instructions. Currently, scoring more than the number of squares in the grid (requires you to cover all white squares) gives a bonus of one of each power-up. Is this what you meant?

5) I have had other feedback about this button problem too so I'm working on a fix.

Thanks again.
(App Store reviewed/feedback greatly appreciated too!)

Chris

**Comment by jsbain** [comment]
i am using the app store version.
also... today, this happened!
http://imgur.com/BOpdi0J

**Comment by chriswilson1982** [comment]
Top of the leaderboard! Nice one! :)

**Comment by jsbain** [comment]
no i meant ... the path was clear, yet it said it wasn't

**Comment by chriswilson1982** [comment]
Oh yeah! Thought maybe the red squares had just dropped away like they do. That's not good, especially with a great score!

Not sure what would have caused that - haven't encountered it myself but will have a look. Anything else unusual at the time?

**Comment by jsbain** [comment]
actually, in retro spect, there must have been a red square blcking that i didn't notice.  when they drop away, the locked blocks go away too, so you don't see the gameboard as it was.

**Comment by chriswilson1982** [comment]
Yeah I wondered about the point of making them drop away - purely aesthetics I guess! :)
